[package]
name = "cranelift-isle-veri"
version = "0.1.0"
edition.workspace = true

[dependencies]
cranelift-codegen-meta = { version = "*", path = "../../codegen/meta" }
env_logger = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ['default'] }
