[package]
name = "cranelift-isle-veri-test-macros"
version = "0.1.0"
publish = false
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { workspace = true, features = ["full"]}
proc-macro2 = "1.0"
proc-macro-error = "1.0"
