[package]
name = "cranelift-isle-veri-aslp"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pest = "2.7.8"
pest_derive = "2.7.8"
enquote = "1.1.0"
clap = { workspace = true }
anyhow = { workspace = true, features = ['std'] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
cranelift-isle-veri-test-macros = { path = "../test-macros" }
reqwest = { workspace = true, features = ["blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
