name: ci

on:
  push:
    branches:
      - mbm/x-rule-chaining
  pull_request:
    branches:
      - mbm/x-rule-chaining

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build -p cranelift-isle -p cranelift-isle-veri
      - name: Test
        run: cargo test -p cranelift-isle -p cranelift-isle-veri

  veri:
    strategy:
      matrix:
        arch: [aarch64, x64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Tools
        run: sudo apt-get install -y z3
      - name: Build
        run: cargo build --release -p cranelift-isle-veri
      - name: Verify
        working-directory: cranelift/isle/veri
        run: ./script/veri.sh -a ${{ matrix.arch }} -p release -t "${RUNNER_TEMP}" -o "${RUNNER_TEMP}"
