name: ci

on:
  push:
    branches:
      - veriisle
  pull_request:
    branches:
      - veriisle

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@1.85
        with:
          targets: wasm32-wasip1,wasm32-unknown-unknown
          components: rustfmt
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Setup Tools Directory
        run: |
          mkdir -p "${{ runner.workspace }}/tools"
          echo "${{ runner.workspace }}/tools/bin" >> $GITHUB_PATH
      - name: Install CVC5
        working-directory: cranelift/isle/veri/veri
        run: ./script/install/cvc5.sh -i "${{ runner.workspace }}/tools" -t "${RUNNER_TEMP}"
      - name: Show CVC5 Version
        run: cvc5 --version
      - name: Install Z3
        working-directory: cranelift/isle/veri/veri
        run: ./script/install/z3.sh -b "${{ runner.workspace }}/tools/bin" -t "${RUNNER_TEMP}"
      - name: Show Z3 Version
        run: z3 --version
      - name: Build
        run: cargo build --features cranelift-isle/printer --package 'cranelift-isle*'
      - name: Test
        run: cargo test --features cranelift-isle/printer --package 'cranelift-isle*'
      - name: Wast Tests
        run: cargo test --test wast
      - name: Format
        run: cargo fmt --check --verbose

  veri:
    strategy:
      matrix:
        arch: [aarch64, x64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: main
      - name: Setup Tools Directory
        run: |
          mkdir -p "${{ runner.workspace }}/tools"
          echo "${{ runner.workspace }}/tools/bin" >> $GITHUB_PATH
      - name: Install CVC5
        working-directory: main/cranelift/isle/veri/veri
        run: ./script/install/cvc5.sh -i "${{ runner.workspace }}/tools" -t "${RUNNER_TEMP}"
      - name: Show CVC5 Version
        run: cvc5 --version
      - name: Install Z3
        working-directory: main/cranelift/isle/veri/veri
        run: ./script/install/z3.sh -b "${{ runner.workspace }}/tools/bin" -t "${RUNNER_TEMP}"
      - name: Show Z3 Version
        run: z3 --version
      - name: Build
        run: cargo build --release -p cranelift-isle-veri
        working-directory: main
      - name: Verify
        working-directory: main/cranelift/isle/veri/veri
        run: ./script/verify/ci.sh -a ${{ matrix.arch }} -p release -t "${RUNNER_TEMP}" -o "${{ runner.workspace }}/output"
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: veri-${{ matrix.arch }}
          path: ${{ runner.workspace }}/output
          if-no-files-found: error
          compression-level: 9
