name: explorer

on:
  push:
    branches:
      - mbm/x-rule-chaining
  workflow_dispatch:

# Sets permissions to allow deployment to Github Pages.
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Tools
        run: sudo apt-get install -y graphviz
      - name: Build Explorer
        working-directory: cranelift/isle/veri
        run: ./script/explorer.sh
        env:
          ISLE_EXPLORER_GRAPHS: 'true'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: cranelift/isle/veri/tmp/explorer
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
